"""This is an autogenerated file of contract functions for the IB API."""

from ContractSamples import Contract

def usStock_aapl():
    contract = Contract()
    contract.symbol = 'AAPL'
    contract.secType = "STK"
    contract.exchange = "SMART"
    contract.currency = "USD"
    setattr(contract, 'conId', 265598)
    return contract


def usStock_abx():
    contract = Contract()
    contract.symbol = 'ABX'
    contract.secType = "STK"
    contract.exchange = "SMART"
    contract.currency = "USD"
    setattr(contract, 'conId', 611060)
    return contract


def usStock_amd():
    contract = Contract()
    contract.symbol = 'AMD'
    contract.secType = "STK"
    contract.exchange = "SMART"
    contract.currency = "USD"
    setattr(contract, 'conId', 4391)
    return contract


def usStock_axp():
    contract = Contract()
    contract.symbol = 'AXP'
    contract.secType = "STK"
    contract.exchange = "SMART"
    contract.currency = "USD"
    setattr(contract, 'conId', 4721)
    return contract


def usStock_ba():
    contract = Contract()
    contract.symbol = 'BA'
    contract.secType = "STK"
    contract.exchange = "SMART"
    contract.currency = "USD"
    setattr(contract, 'conId', 4762)
    return contract


def usStock_baba():
    contract = Contract()
    contract.symbol = 'BABA'
    contract.secType = "STK"
    contract.exchange = "SMART"
    contract.currency = "USD"
    setattr(contract, 'conId', 166090175)
    return contract


def usStock_bac():
    contract = Contract()
    contract.symbol = 'BAC'
    contract.secType = "STK"
    contract.exchange = "SMART"
    contract.currency = "USD"
    setattr(contract, 'conId', 10098)
    return contract


def usStock_bb():
    contract = Contract()
    contract.symbol = 'BB'
    contract.secType = "STK"
    contract.exchange = "SMART"
    contract.currency = "USD"
    setattr(contract, 'conId', 131217639)
    return contract


def usStock_cat():
    contract = Contract()
    contract.symbol = 'CAT'
    contract.secType = "STK"
    contract.exchange = "SMART"
    contract.currency = "USD"
    setattr(contract, 'conId', 5437)
    return contract


def usStock_cbi():
    contract = Contract()
    contract.symbol = 'CBI'
    contract.secType = "STK"
    contract.exchange = "SMART"
    contract.currency = "USD"
    setattr(contract, 'conId', 2730882)
    return contract


def usStock_chk():
    contract = Contract()
    contract.symbol = 'CHK'
    contract.secType = "STK"
    contract.exchange = "SMART"
    contract.currency = "USD"
    setattr(contract, 'conId', 661417)
    return contract


def usStock_csco():
    contract = Contract()
    contract.symbol = 'CSCO'
    contract.secType = "STK"
    contract.exchange = "SMART"
    contract.currency = "USD"
    setattr(contract, 'conId', 268084)
    return contract


def usStock_cvx():
    contract = Contract()
    contract.symbol = 'CVX'
    contract.secType = "STK"
    contract.exchange = "SMART"
    contract.currency = "USD"
    setattr(contract, 'conId', 5684)
    return contract


def usStock_dis():
    contract = Contract()
    contract.symbol = 'DIS'
    contract.secType = "STK"
    contract.exchange = "SMART"
    contract.currency = "USD"
    setattr(contract, 'conId', 6459)
    return contract


def usStock_dwdp():
    contract = Contract()
    contract.symbol = 'DWDP'
    contract.secType = "STK"
    contract.exchange = "SMART"
    contract.currency = "USD"
    setattr(contract, 'conId', 287025078)
    return contract


def usStock_fb():
    contract = Contract()
    contract.symbol = 'FB'
    contract.secType = "STK"
    contract.exchange = "SMART"
    contract.currency = "USD"
    setattr(contract, 'conId', 107113386)
    return contract


def usStock_fcx():
    contract = Contract()
    contract.symbol = 'FCX'
    contract.secType = "STK"
    contract.exchange = "SMART"
    contract.currency = "USD"
    setattr(contract, 'conId', 7089)
    return contract


def usStock_ge():
    contract = Contract()
    contract.symbol = 'GE'
    contract.secType = "STK"
    contract.exchange = "SMART"
    contract.currency = "USD"
    setattr(contract, 'conId', 7516)
    return contract


def usStock_glw():
    contract = Contract()
    contract.symbol = 'GLW'
    contract.secType = "STK"
    contract.exchange = "SMART"
    contract.currency = "USD"
    setattr(contract, 'conId', 7655)
    return contract


def usStock_gs():
    contract = Contract()
    contract.symbol = 'GS'
    contract.secType = "STK"
    contract.exchange = "SMART"
    contract.currency = "USD"
    setattr(contract, 'conId', 4627828)
    return contract


def usStock_hd():
    contract = Contract()
    contract.symbol = 'HD'
    contract.secType = "STK"
    contract.exchange = "SMART"
    contract.currency = "USD"
    setattr(contract, 'conId', 7930)
    return contract


def usStock_hpq():
    contract = Contract()
    contract.symbol = 'HPQ'
    contract.secType = "STK"
    contract.exchange = "SMART"
    contract.currency = "USD"
    setattr(contract, 'conId', 209411801)
    return contract


def usStock_ibm():
    contract = Contract()
    contract.symbol = 'IBM'
    contract.secType = "STK"
    contract.exchange = "SMART"
    contract.currency = "USD"
    setattr(contract, 'conId', 8314)
    return contract


def usStock_intc():
    contract = Contract()
    contract.symbol = 'INTC'
    contract.secType = "STK"
    contract.exchange = "SMART"
    contract.currency = "USD"
    setattr(contract, 'conId', 270639)
    return contract


def usStock_jnj():
    contract = Contract()
    contract.symbol = 'JNJ'
    contract.secType = "STK"
    contract.exchange = "SMART"
    contract.currency = "USD"
    setattr(contract, 'conId', 8719)
    return contract


def usStock_jpm():
    contract = Contract()
    contract.symbol = 'JPM'
    contract.secType = "STK"
    contract.exchange = "SMART"
    contract.currency = "USD"
    setattr(contract, 'conId', 1520593)
    return contract


def usStock_ko():
    contract = Contract()
    contract.symbol = 'KO'
    contract.secType = "STK"
    contract.exchange = "SMART"
    contract.currency = "USD"
    setattr(contract, 'conId', 8894)
    return contract


def usStock_low():
    contract = Contract()
    contract.symbol = 'LOW'
    contract.secType = "STK"
    contract.exchange = "SMART"
    contract.currency = "USD"
    setattr(contract, 'conId', 9199)
    return contract


def usStock_mcd():
    contract = Contract()
    contract.symbol = 'MCD'
    contract.secType = "STK"
    contract.exchange = "SMART"
    contract.currency = "USD"
    setattr(contract, 'conId', 9408)
    return contract


def usStock_mmm():
    contract = Contract()
    contract.symbol = 'MMM'
    contract.secType = "STK"
    contract.exchange = "SMART"
    contract.currency = "USD"
    setattr(contract, 'conId', 9720)
    return contract


def usStock_mrk():
    contract = Contract()
    contract.symbol = 'MRK'
    contract.secType = "STK"
    contract.exchange = "SMART"
    contract.currency = "USD"
    setattr(contract, 'conId', 70101545)
    return contract


def usStock_msft():
    contract = Contract()
    contract.symbol = 'MSFT'
    contract.secType = "STK"
    contract.exchange = "SMART"
    contract.currency = "USD"
    setattr(contract, 'conId', 272093)
    return contract


def usStock_mu():
    contract = Contract()
    contract.symbol = 'MU'
    contract.secType = "STK"
    contract.exchange = "SMART"
    contract.currency = "USD"
    setattr(contract, 'conId', 9939)
    return contract


def usStock_nflx():
    contract = Contract()
    contract.symbol = 'NFLX'
    contract.secType = "STK"
    contract.exchange = "SMART"
    contract.currency = "USD"
    setattr(contract, 'conId', 15124833)
    return contract


def usStock_nke():
    contract = Contract()
    contract.symbol = 'NKE'
    contract.secType = "STK"
    contract.exchange = "SMART"
    contract.currency = "USD"
    setattr(contract, 'conId', 10291)
    return contract


def usStock_nvda():
    contract = Contract()
    contract.symbol = 'NVDA'
    contract.secType = "STK"
    contract.exchange = "SMART"
    contract.currency = "USD"
    setattr(contract, 'conId', 4815747)
    return contract


def usStock_pfe():
    contract = Contract()
    contract.symbol = 'PFE'
    contract.secType = "STK"
    contract.exchange = "SMART"
    contract.currency = "USD"
    setattr(contract, 'conId', 11031)
    return contract


def usStock_pg():
    contract = Contract()
    contract.symbol = 'PG'
    contract.secType = "STK"
    contract.exchange = "SMART"
    contract.currency = "USD"
    setattr(contract, 'conId', 11054)
    return contract


def usStock_sbux():
    contract = Contract()
    contract.symbol = 'SBUX'
    contract.secType = "STK"
    contract.exchange = "SMART"
    contract.currency = "USD"
    setattr(contract, 'conId', 274105)
    return contract


def usStock_slb():
    contract = Contract()
    contract.symbol = 'SLB'
    contract.secType = "STK"
    contract.exchange = "SMART"
    contract.currency = "USD"
    setattr(contract, 'conId', 12200)
    return contract


def usStock_snap():
    contract = Contract()
    contract.symbol = 'SNAP'
    contract.secType = "STK"
    contract.exchange = "SMART"
    contract.currency = "USD"
    setattr(contract, 'conId', 268060148)
    return contract


def usStock_tsla():
    contract = Contract()
    contract.symbol = 'TSLA'
    contract.secType = "STK"
    contract.exchange = "SMART"
    contract.currency = "USD"
    setattr(contract, 'conId', 76792991)
    return contract


def usStock_twtr():
    contract = Contract()
    contract.symbol = 'TWTR'
    contract.secType = "STK"
    contract.exchange = "SMART"
    contract.currency = "USD"
    setattr(contract, 'conId', 137780444)
    return contract


def usStock_txn():
    contract = Contract()
    contract.symbol = 'TXN'
    contract.secType = "STK"
    contract.exchange = "SMART"
    contract.currency = "USD"
    setattr(contract, 'conId', 13096)
    return contract


def usStock_unh():
    contract = Contract()
    contract.symbol = 'UNH'
    contract.secType = "STK"
    contract.exchange = "SMART"
    contract.currency = "USD"
    setattr(contract, 'conId', 13272)
    return contract


def usStock_utx():
    contract = Contract()
    contract.symbol = 'UTX'
    contract.secType = "STK"
    contract.exchange = "SMART"
    contract.currency = "USD"
    setattr(contract, 'conId', 13364)
    return contract


def usStock_v():
    contract = Contract()
    contract.symbol = 'V'
    contract.secType = "STK"
    contract.exchange = "SMART"
    contract.currency = "USD"
    setattr(contract, 'conId', 49462172)
    return contract


def usStock_vz():
    contract = Contract()
    contract.symbol = 'VZ'
    contract.secType = "STK"
    contract.exchange = "SMART"
    contract.currency = "USD"
    setattr(contract, 'conId', 4901)
    return contract


def usStock_wmt():
    contract = Contract()
    contract.symbol = 'WMT'
    contract.secType = "STK"
    contract.exchange = "SMART"
    contract.currency = "USD"
    setattr(contract, 'conId', 13824)
    return contract


def usStock_xom():
    contract = Contract()
    contract.symbol = 'XOM'
    contract.secType = "STK"
    contract.exchange = "SMART"
    contract.currency = "USD"
    setattr(contract, 'conId', 13977)
    return contract

